version: "3.8"
services:
  server:
    build:
      context: "./server"
    ports:
      - "8080:8080"
    env_file:
      - env/serverenv
      - env/postgresenv
    volumes:
      - servervolume:/node_modules
    networks:
      - backend
      - frontend
  client:
    build:
      context: "./client"
    ports:
      - "3000:3000"
    links: 
      - server
    env_file: 
      - env/clientenv
      - env/serverenv
    volumes:
      - clientvolume:/node_module
    depends_on: 
      - server
    networks:
      - frontend
  postgres:
    image: postgres
    env_file:
      - env/postgresenv
    ports:
      - "5432:5432"
    volumes:
      - postgresvolume:/var/lib/postgres/data
      - ./postgresschema/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - backend
    

volumes:
  clientvolume:
  servervolume:
  postgresvolume:
networks:
  backend:
  frontend:
